### ISSUE TITLE
Attaching additional disks during build

### ISSUE THREAD

**Issue by jlsalmon** [cirruslabs/packer-plugin-tart#112]
Hi folks,

When attempting to attach an additional disk during an image build (e.g. `run_extra_args = ["--disk=/dev/disk7"]`) the user is presented with the following error message:

```
failed to parse "diskutil list -plist physical" output: there are more than one physical disk present on the system
```

Would it be possible to alter [the logic](https://github.com/cirruslabs/packer-plugin-tart/blob/main/builder/tart/diskutil_parser.go#L28) to allow multiple disk attachments? My use case for wanting to do this is to attach a disk containing a large pre-existing source code directory (100GB+) and have that code compiled by a Packer provisioning step, thereby creating a tart image containing the compiled binaries. Due to its large size I am not keen on cloning the repo in a provisioning step, rather I would like to re-use the copy that already exists on the host.

As a workaround, I could compile my binaries on the host and copy them into the image, but I would prefer to have the compilation happen inside a tart VM, where the filesystem/dependencies/toolchain are immutable.

(Note: I tried mounting a directory via `--dir`, but run into good old virtiofs bugs during compilation.)

For reference, the output of `diskutil list -plist physical` when an extra disk is attached looks something like this:

```
admin@admins-Virtual-Machine ~ % diskutil list -plist physical
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>AllDisks</key>
	<array>
		<string>disk0</string>
		<string>disk0s1</string>
		<string>disk0s2</string>
		<string>disk2</string>
	</array>
	<key>AllDisksAndPartitions</key>
	<array>
		<dict>
			<key>Content</key>
			<string>GUID_partition_scheme</string>
			<key>DeviceIdentifier</key>
			<string>disk0</string>
			<key>OSInternal</key>
			<false/>
			<key>Partitions</key>
			<array>
				<dict>
					<key>Content</key>
					<string>Apple_APFS_ISC</string>
					<key>DeviceIdentifier</key>
					<string>disk0s1</string>
					<key>DiskUUID</key>
					<string>D2B79297-879E-4461-8DA2-EEA50EA7319A</string>
					<key>Size</key>
					<integer>524288000</integer>
				</dict>
				<dict>
					<key>Content</key>
					<string>Apple_APFS</string>
					<key>DeviceIdentifier</key>
					<string>disk0s2</string>
					<key>DiskUUID</key>
					<string>D5BA624D-182F-40D0-8248-D08508A8D1B3</string>
					<key>Size</key>
					<integer>89475674112</integer>
				</dict>
			</array>
			<key>Size</key>
			<integer>90000000000</integer>
		</dict>
		<dict>
			<key>Content</key>
			<string></string>
			<key>DeviceIdentifier</key>
			<string>disk2</string>
			<key>OSInternal</key>
			<false/>
			<key>Size</key>
			<integer>107164426240</integer>
		</dict>
	</array>
	<key>VolumesFromDisks</key>
	<array/>
	<key>WholeDisks</key>
	<array>
		<string>disk0</string>
		<string>disk2</string>
	</array>
</dict>
</plist>
```

**Comment by edigaryev** [comment]
Please check out the [new `1.8.1` release](https://github.com/cirruslabs/packer-plugin-tart/releases/tag/v1.8.1), it includes the fix for your issue.

**Comment by jlsalmon** [comment]
Thank you for the swift and efficient resolution as always @edigaryev! 🎉
