### ISSUE TITLE
No cleanup after failure & ctrl-c stops the VM

### ISSUE THREAD

**Issue by sparshev** [cirruslabs/packer-plugin-tart#115]
Two behavioral issues here: No cleanup after failure and Ctrl-C stops the VM:

1. When the packer is failed to build the VM (`macos1306` in this case) - it leaves the image in local registry:
   ```
   ...
   Cancelling build after receiving interrupt
   2024/02/29 12:41:53 Cancelling builder after context cancellation context canceled
   2024/02/29 12:41:53 packer-plugin-ansible_v1.1.1_x5.0_darwin_arm64 plugin: 2024/02/29 12:41:53 Received interrupt signal (count: 1). Ignoring.
   2024/02/29 12:41:53 packer-provisioner-shell plugin: Received interrupt signal (count: 1). Ignoring.
   2024/02/29 12:41:53 packer-plugin-tart_v1.8.1_x5.0_darwin_arm64 plugin: 2024/02/29 12:41:53 Received interrupt signal (count: 1). Ignoring.
   ==> tart-cli: Failed to run the boot command: context canceled
   ==> tart-cli: Failed to run the boot command: context canceled
   ==> tart-cli: Step "stepRun" failed
   ==> tart-cli: [c] Clean up and exit, [a] abort without cleanup, or [r] retry step (build may fail even if retry succeeds)? c
   ==> tart-cli: Waiting for the tart process to exit...
   ==> tart-cli: Connection reset by peer (os error 54)
   ==> Wait completed after 4 minutes 34 seconds
   Build 'tart-cli' errored after 4 minutes 34 seconds: Failed to run the boot command: context canceled
   
   ==> Wait completed after 4 minutes 34 seconds
   2024/02/29 12:42:10 waiting for all plugin processes to complete...
   Cleanly cancelled builds after being interrupted.
   2024/02/29 12:42:10 /Users/admin/.config/packer/plugins/github.com/cirruslabs/tart/packer-plugin-tart_v1.8.1_x5.0_darwin_arm64: plugin process exited
   2024/02/29 12:42:10 /Users/admin/git/aquarium-bait/.bin/packer: plugin process exited
   2024/02/29 12:42:10 /Users/admin/.config/packer/plugins/github.com/hashicorp/ansible/packer-plugin-ansible_v1.1.1_x5.0_darwin_arm64: plugin process exited
   ...
   $ tart list
   Source Name      Size State  
   local  macos1306 15   stopped
   local  test1     23   stopped
   ...
   ```
   Usually build plugins cleans up after that - so maybe there is some sort of issue in the cleanup logic?

2. Ctrl-C during packer execution for some reason stops the VM. Should not happen - VM need to be stopped only in cleanup stage when user decided to cleanup the environment.

**Comment by fkorotkov** [comment]
Yeah, we leave so you can debug things. Maybe we can change the default behaviour to cleanup and have a flag that will persist VMs on failures.

**Comment by sparshev** [comment]
Yeah, that's why I run debug images building with `packer -on-error=ask` - and it will ask me what to do with the VM - just like I described in the log:
```
==> tart-cli: Step "stepRun" failed
==> tart-cli: [c] Clean up and exit, [a] abort without cleanup, or [r] retry step (build may fail even if retry succeeds)? c
```
So when I choose "c" - it should cleanup and when I choose "a" - just abort and leave the VM there for debugging.

**Comment by sparshev** [comment]
Oh, and I also noticed that VM stops when I press "Ctrl-C" in terminal during the process of the build to stop the packer execution - the VM should not stop because of that, only during the cleanup process if it was chosen.

**Comment by fkorotkov** [comment]
Sounds good. 👌 I'll check these behaviors next week. Sorry for the slight inconveniences in the meantime.

**Comment by sparshev** [comment]
No worries, for manual run they are fine, but for future automation could be a bit troublesome...

**Comment by sparshev** [comment]
Updated since Ctrl-C issue was not addressed here, will create another ticket when will test it.

**Comment by edigaryev** [comment]
> Updated since Ctrl-C issue was not addressed here, will create another ticket when will test it.

Please see https://github.com/cirruslabs/packer-plugin-tart/pull/120#issuecomment-1997239550.
