### ISSUE TITLE
Duplicated code between step_run and step_create_linux_vm

### ISSUE THREAD

**Issue by torarnv** [cirruslabs/packer-plugin-tart#127]
Looks like the `runInstaller` part of step_create_linux_vm is duplicating code from step_run. I can clean this up, but want to verify if there are other plans in this area before I dig in. Thanks :)

**Comment by fkorotkov** [comment]
Indeed! It seems we can reuse code from `step_run` and just handle `FromISO` as well. Just add 

```go
for _, iso := range config.FromISO {
  runArgs = append(runArgs, fmt.Sprintf("--disk=%s:ro", iso))
}
```

to `step_run` and I think we'll be good to go.

A PR will be much appreciated but if you don't have time we can also take it from you.

**Comment by torarnv** [comment]
Cool, thanks! I'll have a look tomorrow then :)

**Comment by torarnv** [comment]
Doesn't look like I can assign issues, but consider the issue "assigned" 😄
