### ISSUE TITLE
Software Update doesn't work in VMs from tart packer plugin

### ISSUE THREAD

**Issue by jfro** [cirruslabs/packer-plugin-tart#140]
I've only tested in macOS 13 as that's our current CI OS that we're likely stuck with for a little while.

1. Setup a simple bare bones packer tart config: https://gist.github.com/jfro/4f9559d462bcc67238e4617d34730680
2. Run packer build on it
3. Once complete, start it up with tart
4. Try to run software update to get it to latest patch
5. End up with personalization error (console reports an error with recovery partition)

I don't see anything in my simple config that should affect SU, but as a comparison, creating a fresh VM via tart itself doesn't have this problem.

**Comment by edigaryev** [comment]
Hi Jeremy!

Please check out the new [Packer Plugin Tart `1.11.0` release](https://github.com/cirruslabs/packer-plugin-tart/releases/tag/v1.11.0).

It now supports [the `recovery_partition ` option](https://developer.hashicorp.com/packer/integrations/cirruslabs/tart/latest/components/builder/tart#optional:), which in your case could be set to `"keep"` or `"relocate"` to avoid removing the recovery partition.

**Comment by jfro** [comment]
thank you, that did the trick!
