### ISSUE TITLE
Add option to mount folders

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/packer-plugin-tart#15]
This way we can mount a local folder with Xcode XIPs so we don't need to download it each time:

https://github.com/cirruslabs/macos-image-templates/blob/439e73a85f64cf2f297764062a7f6557233df74f/templates/xcode.pkr.hcl#L72

**Comment by nathreed** [comment]
I was able to solve my immediate CLT installation problem using the `file` provisioner. Something like this might be able to be used for Xcode too (copying an Xcode DMG into the VM, perhaps?) without needing to add support to "mount" directories like they were disk images.

```
provisioner "file" {
    source = "Command_Line_Tools_for_Xcode_14.1.dmg"
    destination = "/tmp/clt.dmg"
  }

provisioner "shell" {
    inline = [
      "hdiutil attach /tmp/clt.dmg",
      "sudo installer -pkg \"/Volumes/Command Line Developer Tools/Command Line Tools.pkg\" -target /",
      "hdiutil detach \"/Volumes/Command Line Developer Tools\"",
      "rm /tmp/clt.dmg"
    ]
  }
```
