### ISSUE TITLE
packer build templates/vanilla-sequoia.pkr.hcl failed with missing config.json

### ISSUE THREAD

**Issue by eecsmap** [cirruslabs/packer-plugin-tart#168]
Failed when running: `packer build templates/vanilla-sequoia.pkr.hcl`

```
==> tart-cli.tart: Cleaning up virtual machine...
    tart-cli.tart: failed to open lock file file:///Users/cm/.tart/vms/sequoia-vanilla/config.json: No such file or directory
```

**Comment by edigaryev** [comment]
Thanks for posting some more details!

I think the reason for the Packer build failure is this line:

```
Error: A software update is required to complete the installation. Installation requires a software update.
```

As for the `Cleaning up virtual machine` and `failed to open lock file`, this is purely cosmetic, I've created two PRs below to address these UX issues:

* https://github.com/cirruslabs/packer-plugin-tart/pull/169
* https://github.com/cirruslabs/tart/pull/910

**Comment by eecsmap** [comment]
Just FYI. I reimage the machine with macOS 15.0 then the issue is gone. It seems only show up in my macOS 14+ box.
