### ISSUE TITLE
Add ability to send macOS-specific modifier keys (Command, Option) to `boot_command`

### ISSUE THREAD

**Issue by hisaac** [cirruslabs/packer-plugin-tart#174]
## Description

I have a small quality of life improvement I'd love to see in this plugin: The ability to use correct references to macOS-specific modifier keys (Command and Option keys) in the `boot_command`.

Specifically, what I'd like to have is:

1. The ability to use `<leftCmdOn>` and its left/right off/on variants to send the Command key.
2. The ability to use `<leftOptOn>` and its left/right off/on variants to send the Option key.

Right now, `<leftAlt>` an `<rightAlt>` both map to left and right Command respectively, so I assume these could just be aliased somehow.

I haven't figured out how to send an Option key command yet though, so I'm not sure how that would be implemented.

I'm willing to do this work myself if someone could first give me some guidance or ideas on where and how this modification might be made.

**Comment by hisaac** [comment]
I'm not sure at what layer these changes would need to be made, so I've also opened a matching issue on the hashicorp/packer-plugin-sdk repo: https://github.com/hashicorp/packer-plugin-sdk/issues/266

**Comment by edigaryev** [comment]
Hi Isaac 👋 

https://github.com/hashicorp/packer-plugin-sdk/issues/266 is the correct place to request these enhancements as we simply pass the `boot_command` to Packer Plugin SDK for parsing.

>I haven't figured out how to send an Option key command yet though, so I'm not sure how that would be implemented.

A search for [`repo:hashicorp/packer-plugin-sdk leftAlt`](https://github.com/search?q=repo%3Ahashicorp%2Fpacker-plugin-sdk%20leftAlt&type=code) could be a good starting point.

**Comment by hisaac** [comment]
Sounds good, thanks for the extra info @edigaryev. I did try to do some changes to the packer-plugin-sdk locally in hopes of getting the Option key working, but didn't have much success. I'll see if my question on that repo gets any traction.
