### ISSUE TITLE
TART_HOME is ignored in some places

### ISSUE THREAD

**Issue by bldrvnlw** [cirruslabs/packer-plugin-tart#38]
Using TART_HOME to redirect the build to another drive fails in steps such as  https://github.com/cirruslabs/packer-plugin-tart/blob/main/builder/tart/step_disk_file_prepare.go#L31 where the code assumes that the homeDir is simply os.UserHomeDir().

**Comment by hwo411** [comment]
Would be great if you fix it. Have to use an external drive for VMs, so TART_HOME is changed. As a workaround a symlink can be used.

**Comment by bldrvnlw** [comment]
@hwo411 - re. symlink - Indeed that was my temporary solution.  Nice to see that theve tackled this.
