### ISSUE TITLE
Document http_directory

### ISSUE THREAD

**Issue by HariSekhon** [cirruslabs/packer-plugin-tart#75]
It seems there is a new `http_directory` setting but it's not documented anywhere that I can find.

When I add it I find that I get this output:

```
==> ubuntu-22.04.tart-cli.ubuntu: Starting HTTP server on port 8232
```

so it seems to work on the latest plugin, I basically guessed this from issues #29, #58, #63.

**Comment by HariSekhon** [comment]
I can't see where the `http_directory` setting is documented, I can't see it here:

https://github.com/cirruslabs/packer-plugin-tart/blob/main/README.md#configuration

or here:

https://developer.hashicorp.com/packer/plugins/builders/tart

**Comment by edigaryev** [comment]
>https://developer.hashicorp.com/packer/plugins/builders/tart

It should be only here due to `@include` usage.

I guess we have to wait some time until the HashiCorp's website pulls the [new version](https://github.com/cirruslabs/packer-plugin-tart/releases/tag/v1.4.0).

**Comment by edigaryev** [comment]
@HariSekhon the new docs are now live at https://developer.hashicorp.com/packer/plugins/builders/tart.

**Comment by HariSekhon** [comment]
@edigaryev Thanks - there is a slight formatting bug showing the backticks here:

```
`wget http://{{ .HTTPIP }}:{{ .HTTPPort }}/foo/bar/preseed.cfg`
```

Would it be possible to include an example usage as I believe this will be the common case if you look at how the other builders are used.

**Comment by edigaryev** [comment]
>there is a slight formatting bug showing the backticks here

I've created https://github.com/hashicorp/packer-plugin-sdk/pull/191 to address this.

>Would it be possible to include an example usage as I believe this will be the common case if you look at how the other builders are used.

Can you provide concrete scenarios that you would like to be documented as examples?

Creating a separate ticket for this would be a good idea.
