### ISSUE TITLE
add tart create --from-ipsw to as an option in  packer source

### ISSUE THREAD

**Issue by trodemaster** [cirruslabs/packer-plugin-tart#8]
This plugin currently creates new VMs by doing a tart clone of an existing artifact from a registry. Doing a build starting from an ipsw local file or URL would also be desirable. 

Maybe add an ipsw option
 from_ipsw = "/path/to/image.ipsw"

When configured, the plugin would exec create instead of the current clone function
tart create --from-ipsw "/path/to/image.ipsw"

Tart and this plugin are really cool! thanks for releasing them!

**Comment by fkorotkov** [comment]
FYI you can provide a URL even right now. `clone` command will try to pull a VM if it's not already presented locally.

For the IPSW part I've created https://github.com/cirruslabs/tart/issues/101. First we need to automate the creation process.

**Comment by fkorotkov** [comment]
I think the issue is covered by #21
