### ISSUE TITLE
Allow --resolver option when getting VM's IP

### ISSUE THREAD

**Issue by PRESIDENT810** [cirruslabs/packer-plugin-tart#96]
I'm using --network-bridged=en0 when to launch my VM, and according to https://github.com/cirruslabs/tart/issues/472, I should use --resolver=arp to get VM's ip address, because the default dhcp doesn't work for bridged network.

However, this packer plugin seems not to be providing this option currently, and if I pass run_extra_args = ["--net-bridged=en0"] in the source block, `packer build` cannot find the VM's ip address correctly (because it's using dhcp resolver).

Is it possible to add a option to allow passing `--resolver` option to this plugin? Thanks!

**Comment by fkorotkov** [comment]
We can probably add something like `ip_extra_args`.
